### ISSUE TITLE
GlobalConfigのバグ

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/00-Atlas-ac#107]
例えば
- 80/80でGlobalに設定する
- 個別で100/100が入った状態で保存する
- 個別のConfigが80/80に自動で設定される
- このあともう一回同じ操作をする
- 64/64で設定される

たぶん掛け算とセットするテキストをしくっている
f○cking!!!
@Dai1678

**Comment by multiverse2011** [comment]
@Dai1678 これ僕が言った仕様理解してた？

**Comment by Dai1678** [comment]
↑の再現方法よくわからんのだが、もう一回同じ操作をするってとこ詳しく

**Comment by Thiroaki** [comment]
パワーの指定をシークバーにしてGlobalConfig * シークバーの倍率で指定出来るようにしました
それに伴いモデルクラスも少し変更しました

**Comment by multiverse2011** [comment]
@Thiroaki これもうできてる？

**Comment by Thiroaki** [comment]
できたのでclose
