### ISSUE TITLE
ペアリングしている状態かつブロックなしの状態のときに実行するとクラッシュ

### ISSUE THREAD

**Issue by Dai1678** [t-robop/00-Atlas-ac#130]
機体とBluetoothペアリングしている　かつ　ブロックが何もないときに実行ボタンを押すと
アプリがクラッシュする

getForDeployed() でヌルポおきている

**Comment by Dai1678** [comment]
branch hotfix/NoBrockState で解決済み
6/24イベントには間に合わないので、終了次第プルリク出します

**Comment by multiverse2011** [comment]
Dk2がやってくれた
