### ISSUE TITLE
for文のイメージ作成・実行回数編集ダイアログ作成

### ISSUE THREAD

**Issue by Dai1678** [t-robop/00-Atlas-ac#20]
新しくfor文用のデバッグButtonを追加してスクリプトリストに追加できるようにする
追加されたfor文の項目をクリックしたら、繰り返し回数を設定するダイアログを表示する

**Comment by multiverse2011** [comment]
こちら進捗どうですか

**Comment by Dai1678** [comment]
何も進んでないので今週中には成果出したいね

**Comment by multiverse2011** [comment]
orderIdが5のときloopのスタート、6のときloopのエンドで実装予定
orderIdの決め方がイケてない感ある

**Comment by y-ogawara** [comment]
orderIdはあるでぃーの解釈用で使いたいからモデルに新しい変数追加してほしい。

boolでforなのかどうか
intでループ数

**Comment by multiverse2011** [comment]
これloopのスタートとエンドの判定どうやるのがいいんですかね

**Comment by y-ogawara** [comment]
boolをenumにして実装かな
for開始 for終わりみたいな
変数が違う意味を持つことだけは避けたい

**Comment by y-ogawara** [comment]
これ、構文チェック機構を作らないと、for文始めはあっても、終わりは無い。
みたいなときが出てきて死にそう
