### ISSUE TITLE
ListView内の並び替え処理の追加

### ISSUE THREAD

**Issue by Dai1678** [t-robop/00-Atlas-ac#27]
ボタンを押して追加した命令を、ドラッグで動かして上から好きな順番に並び替えられるようにする

**Comment by multiverse2011** [comment]
listviewだと
[https://github.com/nhaarman/ListViewAnimations](https://github.com/nhaarman/ListViewAnimations)
などがあるみたいだがdeprecatedなのでかなり微妙＆https://github.com/t-robop/ScriptRobotController/issues/51の話がゴリゴリでなおすことになる。

根本的にはRecyclerViewでcardstack的なものを作るしかなさそう。
https://developer.android.com/guide/topics/ui/layout/recyclerview?hl=ja

**Comment by multiverse2011** [comment]
いま着手しました
