### ISSUE TITLE
NavigationDrawerを引っ張り出すアイコンの追加

### ISSUE THREAD

**Issue by Dai1678** [t-robop/00-Atlas-ac#29]
![1](https://user-images.githubusercontent.com/19250035/39181541-f3b3f226-47f4-11e8-894e-7321b9327954.jpg)

ScrollViewで縦に命令を並べる
Drawerにある命令パーツをタップして命令を追加できる

**Comment by Dai1678** [comment]
残タスク
・ダイアログのレイアウト適用
・Drawer出す三本線のアイコン
・ループ処理の画像作成

**Comment by multiverse2011** [comment]
ドロワーの三本線をつけたい
@VaioYuki に頼もうかなと

**Comment by multiverse2011** [comment]
これアイコンから引っ張りだすのわかりにくいのでmainに直接表示でいいよね
#94 に統合します
