### ISSUE TITLE
for文がおかしい

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/00-Atlas-ac#95]
for文を呼ぶと3回ぐらいまでは動く
5回とか10回になると死亡する

**Comment by multiverse2011** [comment]
@TaigaNatto これ早めに直して

**Comment by TaigaNatto** [comment]
ロボット無いからわからんけど、5重とか10重ってこと？
Android側の問題なら単純にメモリ不足、ロボット側なら膨大なデータの受信で死んでるんじゃね

**Comment by y-ogawara** [comment]
@TaigaNatto 
これ、atlasだから西村のやつまだ適応されてない気がする、適応してほしいって意味かと

**Comment by y-ogawara** [comment]
#101 で修正したので閉じます。
