### ISSUE TITLE
グローバルでの速度調節

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/00-Atlas-ac#97]
- ハードウェアで速度を安定化させるのは無理なのでプログラム的に調節する
- グローバルに値が設定できるようにする
- 現状存在する速度調節はグローバルの値に対しての相対的なものにする

**Comment by Dai1678** [comment]
@multiverse2011 
基礎速度値(100とか) + 加算速度値(+50とか)
って感じ？
これどちらの値もアプリ側で編集できるようにするの？

**Comment by multiverse2011** [comment]
例えばグローバルに保持するのが100、今のUIで設定したのが80だとしたら実際に出力されるのが100*0.8=80みたいなイメージ

どちらの値もアプリで設定可能。グローバルな値は僕らで設定して今までのUIで微調整するのは子供がやるイメージ

**Comment by Dai1678** [comment]
↑の仕様は理解したけど、そもそも子どもにパワー値設定させる必要性ってあるんかな？
issue #43 でも挙げてる話だけど。
体験者はブロックの実行時間を工夫してコースを走らせるのが目的なのでは
もともと速度値の調整機能は電池の消耗によって片方のタイヤのパワーが弱くなったときに微調整するため実装したつもりなんだが

**Comment by multiverse2011** [comment]
これに関しては進みながら曲がるを実現したいところはある

**Comment by multiverse2011** [comment]
どっちにしろグローバルで値を設定するやつは作っとかないと

**Comment by Dai1678** [comment]
なーる、それなら調整させる理由になる
ってか、なんで出力値の計算方法が足し算じゃなくて掛け算なの？

**Comment by multiverse2011** [comment]
えっとそれに関してはベースの値に対して相対的に決めたいっていう意味
僕の考えがあってるかはわからん
